server:
  port: 9005
spring:
  application:
    name: client-service
  main:
     allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/clients_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  zipkin:
   base-url: http://localhost:9411
  sleuth:
   sampler:
    probability: 1
    
keycloak:
  realm: formation-ms
  auth-server-url: http://localhost:8080/auth
  resource: client-app
  credentials:
    secret: efc0220f-cc45-4d88-97b0-e23bea1df4c6
  principal-attribute: preferred_username
  bearer-only: true

swagger-ui:
  client: swagger-ui
  secret: 445a4d63-4a42-42dd-ab17-95636c2effcf
eureka:
 client:
  serviceUrl:
   default: http://localhost:8761
   
feign:
 hystrix:
  enabled: false
---
spring:
  profiles: test
  datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: sa
        driver-class-name: org.h2.Driver
  jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate :
          ddl-auto: create